Controllers/PlaylistController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicPlayer.Data;
using MusicPlayer.Models;

namespace MusicPlayer.Controllers;

[Authorize]
public class PlaylistController : BaseController<PlaylistController>
{
    public PlaylistController(ApplicationDbContext context, UserManager<IdentityUser> userManager, ILogger<PlaylistController> logger) : base(context, userManager, logger)
    {
    }

    public async Task<IActionResult> Index()
    {
        var query = _context.Playlists.Where(p => p.User == GetCurrentUser());
        return View(await query.ToListAsync());
    }

    public async Task<IActionResult> Details(int Id)
    {
        var playlist = await _context.Playlists.FindAsync(Id);
        if (playlist == null)
        {
            return NotFound();
        }

        var query = _context.PlaylistSongs.Where(p => p.Playlist == playlist)
            .Include(p => p.Song)
            .Include(p => p.Playlist);

        var temp = new PlaylistDetails
        {
            Playlist = playlist,
            Songs = await query.ToListAsync()
        };

        return View(temp);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Store(Playlist playlist)
    {
        playlist.User = GetCurrentUser();
        _context.Add(playlist);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Edit(int Id)
    {
        var playlist = await _context.Playlists.FindAsync(Id);
        if (playlist == null)
        {
            NotFound();
        }

        return View(playlist);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(Playlist playlist)
    {
        _context.Playlists.Update(playlist);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int Id)
    {
        var playlist = await _context.Playlists.FindAsync(Id);
        if (playlist == null)
        {
            NotFound();
        }

#pragma warning disable CS8604 // Possible null reference argument.
        _context.Playlists.Remove(playlist);
#pragma warning restore CS8604 // Possible null reference argument.

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<List<Song>> SearchSong([FromQuery(Name = "name")] string name)
    {
        var request = _context.Songs.Where(s => s.Name.Contains(name));
        return await request.ToListAsync();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<RedirectToActionResult> AddSong(int Id, int songId)
    {
        var playlist = await _context.Playlists.FindAsync(Id);
        var song = await _context.Songs.FindAsync(songId);

        if (playlist == null || song == null)
        {
            NotFound();
        }

#pragma warning disable CS8601 // Possible null reference assignment.
        var playlistSong = new PlaylistSong
        {
            Playlist = playlist,
            Song = song
        };
#pragma warning restore CS8601 // Possible null reference assignment.
        _context.PlaylistSongs.Add(playlistSong);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Details), new { @id = Id });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteSong(int Id, int playlistSongId)
    {
        var song = await _context.PlaylistSongs.FindAsync(playlistSongId);
        if (song == null)
        {
            NotFound();
        }

#pragma warning disable CS8604 // Possible null reference argument.
        _context.PlaylistSongs.Remove(song);
#pragma warning restore CS8604 // Possible null reference argument.
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Details), new { @id = Id });
    }

    public async Task<List<PlaylistSong>> GetPlaylistSongs(int Id)
    {
        var query = _context.PlaylistSongs.Where(p => p.Playlist.ID == Id)
            .Include(p => p.Playlist)
            .Include(p => p.Song);

        return await query.ToListAsync();
    }

    public async Task<List<Playlist>> GetAllMyPlaylist()
    {
        var query = _context.Playlists.Where(p => p.User == GetCurrentUser());

        return await query.ToListAsync();
    }
}

Controllers/SongController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicPlayer.Data;
using MusicPlayer.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace MusicPlayer.Controllers;

[Authorize]
public class SongController : BaseController<SongController>
{
    [Obsolete]
    private readonly IHostingEnvironment _environment;
    private readonly string _baseDir;

    [Obsolete]
    public SongController(ApplicationDbContext context, UserManager<IdentityUser> userManager, ILogger<SongController> logger, IHostingEnvironment environment) : base(context, userManager, logger)
    {
        _environment = environment;
        _baseDir = environment.ContentRootPath;
    }

    public async Task<IActionResult> Index()
    {
        var user = GetCurrentUser();
        var query = _context.Songs.Where(s => s.User == user);

        return View(await query.ToListAsync());
    }

    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Upload(IEnumerable<IFormFile> files, string? songUrlName, string? url)
    {
        if (url != null && songUrlName != null)
        {
            var song = new Song
            {
                Name = songUrlName,
                Path = url,
                User = GetCurrentUser()
            };

            _context.Add(song);
            await _context.SaveChangesAsync();
        }
        else if (files.Count() != 0)
        {
            var absolutePath = GetAbsolutePath();

            foreach (var file in files)
            {
                if (!Directory.Exists(absolutePath))
                {
                    Directory.CreateDirectory(absolutePath);
                }

                await using (var fileStream = new FileStream(Path.Combine(absolutePath, file.FileName), FileMode.Create,
                                 FileAccess.Write))
                {
                    await file.CopyToAsync(fileStream);

                    var songName = GetFileName(file.FileName, ".mp3");

                    var song = new Song
                    {
                        Name = songName,
                        Path = file.FileName,
                        User = GetCurrentUser()
                    };

                    _context.Add(song);
                    await _context.SaveChangesAsync();
                }
            }
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var song = await _context.Songs.FindAsync(id);
        if (song == null)
        {
            return RedirectToAction(nameof(Index));
        }

        var absolutePath = GetAbsolutePath();
        System.IO.File.Delete(Path.Combine(absolutePath, song.Path));

        _context.Songs.Remove(song);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<RedirectToActionResult> AddSongToPlaylist(int Id, int playlistId)
    {
        var song = await _context.Songs.FindAsync(Id);
        var playlist = await _context.Playlists.FindAsync(playlistId);

        if (song == null || playlist == null)
        {
            NotFound();
        }

#pragma warning disable CS8601 // Possible null reference assignment.
        var playlistSong = new PlaylistSong
        {
            Playlist = playlist,
            Song = song
        };
#pragma warning restore CS8601 // Possible null reference assignment.
        _context.PlaylistSongs.Add(playlistSong);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    private string GetAbsolutePath()
    {
        var user = GetCurrentUser();
        var path = $"wwwroot{Path.DirectorySeparatorChar}musics{Path.DirectorySeparatorChar}{user.Id}";
        var absolutePath = Path.Join(_baseDir, path);

        return absolutePath;
    }

    private string GetFileName(string fileName, string substring)
    {
        var indexOfSubstring = fileName.IndexOf(substring, StringComparison.Ordinal);
        var goodFileName = fileName.Remove(indexOfSubstring, substring.Length);

        return goodFileName;
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject UserManager<IdentityUser> UserManager
@inject SignInManager<IdentityUser> SignInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicPlayer</title>
    <link href="~/lib/favicon.ico" rel="favicon.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/night.css" id="theme-link" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicPlayer.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/4f3834f0ec.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" id="text-darkmode" asp-controller="Home" asp-action="Index">MusicPlayer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="text-darkmode" asp-area="" asp-controller="Playlist" asp-action="Index">
                                    <i class="fa fa-list mr-5" id="icon-padding-right"></i>Playlist
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="text-darkmode" asp-area="" asp-controller="Song" asp-action="Index">
                                    <i class="fa fa-music mr-5" id="icon-padding-right"></i> Songs
                                </a>
                            </li>
                        }
                        <li>
                            <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" id="theme-button">Night</button>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="content-wrapper">
        <div class="container">
            <main role="main" class="container pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <!-- Player -->
    @if (SignInManager.IsSignedIn(User))
    {
        <div class="d-flex flex-column align-items-center">
            <div class="p-2">
                <div class="d-flex flex-row">
                    <div class="h-full d-flex align-items-center">
                        <span style="padding-right: 5px; font-size: 1.2rem;">Currently playing :</span>
                        <span class="ml-5" id="songInProgressText" style="font-style: italic; font-size: 1.2rem;"> </span>
                    </div>
                </div>
            </div>
            <div class="p-2">
                <button style="background-color: white;" id="previousSong" class="me-1 btn" onclick="previousPlaylistSong()">
                    <i class="fa fa-backward"></i>
                </button>
                <button style="background-color: white;" id="pauseButton" class="me-1 btn" onclick="pauseSong()">
                    <i class="fa fa-play"></i>
                </button>
                <button style="background-color: white;" id="nextSong" class="me-1 btn" onclick="nextPlaylistSong()">
                    <i class="fa fa-forward"></i>
                </button>
                <button style="background-color: white;" class="btn" onclick="stopSong()">
                    <i class="fa fa-stop"></i>
                </button>
                <input id="volumeSlider"
                   type="range"
                   name="volume-slider"
                   min="0"
                   max="100"
                   value="50" />
                <button onclick="toggleMute()" id="toggleMuteBtn" class="ml-5 btn">
                    <i class="fa fa-volume-off"></i>
                </button>
            </div>

            <div class="col-4 d-flex justify-content-end ">
            </div>

            <div class="mb-3">
                <div id="waveform" style="width: 500px; height: 50px;"></div>
            </div>
        </div>
    }

    <footer class="border-top footer text-muted" id="text-darkmode">
        <div class="container">
            &copy; 2022 - MusicPlayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/theme.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/wavesurfer.js"></script>
    @if (SignInManager.IsSignedIn(User))
    {
        <script>
            window.userId = "@UserManager.FindByNameAsync(User?.Identity?.Name).Result?.Id"
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>